package com.entity;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table book
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class Book {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.book_id
     *
     * @mbg.generated
     */
    private Integer bookId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.book_name
     *
     * @mbg.generated
     */
    private String bookName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.book_price
     *
     * @mbg.generated
     */
    private Double bookPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.book_desc
     *
     * @mbg.generated
     */
    private String bookDesc;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.book_id
     *
     * @return the value of book.book_id
     *
     * @mbg.generated
     */
    public Integer getBookId() {
        return bookId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.book_id
     *
     * @param bookId the value for book.book_id
     *
     * @mbg.generated
     */
    public void setBookId(Integer bookId) {
        this.bookId = bookId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.book_name
     *
     * @return the value of book.book_name
     *
     * @mbg.generated
     */
    public String getBookName() {
        return bookName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.book_name
     *
     * @param bookName the value for book.book_name
     *
     * @mbg.generated
     */
    public void setBookName(String bookName) {
        this.bookName = bookName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.book_price
     *
     * @return the value of book.book_price
     *
     * @mbg.generated
     */
    public Double getBookPrice() {
        return bookPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.book_price
     *
     * @param bookPrice the value for book.book_price
     *
     * @mbg.generated
     */
    public void setBookPrice(Double bookPrice) {
        this.bookPrice = bookPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.book_desc
     *
     * @return the value of book.book_desc
     *
     * @mbg.generated
     */
    public String getBookDesc() {
        return bookDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.book_desc
     *
     * @param bookDesc the value for book.book_desc
     *
     * @mbg.generated
     */
    public void setBookDesc(String bookDesc) {
        this.bookDesc = bookDesc;
    }
}