package com.entity;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table teacher
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class Teacher {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.code
     *
     * @mbg.generated
     */
    private Integer code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.age
     *
     * @mbg.generated
     */
    private Integer age;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.birthday
     *
     * @mbg.generated
     */
    private LocalDate birthday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.sal
     *
     * @mbg.generated
     */
    private BigDecimal sal;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.student
     *
     * @mbg.generated
     */
    private Long student;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.clazz
     *
     * @mbg.generated
     */
    private Integer clazz;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.birthWay
     *
     * @mbg.generated
     */
    private Date birthway;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.code
     *
     * @return the value of teacher.code
     *
     * @mbg.generated
     */
    public Integer getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.code
     *
     * @param code the value for teacher.code
     *
     * @mbg.generated
     */
    public void setCode(Integer code) {
        this.code = code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.name
     *
     * @return the value of teacher.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.name
     *
     * @param name the value for teacher.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.age
     *
     * @return the value of teacher.age
     *
     * @mbg.generated
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.age
     *
     * @param age the value for teacher.age
     *
     * @mbg.generated
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.id
     *
     * @return the value of teacher.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.id
     *
     * @param id the value for teacher.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.birthday
     *
     * @return the value of teacher.birthday
     *
     * @mbg.generated
     */
    public LocalDate getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.birthday
     *
     * @param birthday the value for teacher.birthday
     *
     * @mbg.generated
     */
    public void setBirthday(LocalDate birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.sal
     *
     * @return the value of teacher.sal
     *
     * @mbg.generated
     */
    public BigDecimal getSal() {
        return sal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.sal
     *
     * @param sal the value for teacher.sal
     *
     * @mbg.generated
     */
    public void setSal(BigDecimal sal) {
        this.sal = sal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.student
     *
     * @return the value of teacher.student
     *
     * @mbg.generated
     */
    public Long getStudent() {
        return student;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.student
     *
     * @param student the value for teacher.student
     *
     * @mbg.generated
     */
    public void setStudent(Long student) {
        this.student = student;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.clazz
     *
     * @return the value of teacher.clazz
     *
     * @mbg.generated
     */
    public Integer getClazz() {
        return clazz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.clazz
     *
     * @param clazz the value for teacher.clazz
     *
     * @mbg.generated
     */
    public void setClazz(Integer clazz) {
        this.clazz = clazz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.birthWay
     *
     * @return the value of teacher.birthWay
     *
     * @mbg.generated
     */
    public Date getBirthway() {
        return birthway;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.birthWay
     *
     * @param birthway the value for teacher.birthWay
     *
     * @mbg.generated
     */
    public void setBirthway(Date birthway) {
        this.birthway = birthway;
    }
}